Repository DIT113-V22/group-02, pull requests merged in 2022-05, with the labels that each got.

#63 Bug fix for wrong collision of smartcar with dummy cars
  mod/mods/PocketParkingTerrain.tscn
  mod/ppmod.pck
Labels: bug, sprint2

#65 #47 straight parking in parking space
  .DS_Store
  .gitignore
  arduino/.DS_Store
  arduino/smartcar/.DS_Store
  arduino/smartcar/smartcar.ino
Labels: sprint2

#72 59 control car with a joystick
  .DS_Store
  SmartCarApplication/app/build.gradle
  SmartCarApplication/app/lib/joystickjhr.aar
  SmartCarApplication/app/src/main/java/com/example/smartcarapplication/MainActivity.java
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
Labels: sprint2

#73 changes behavior of obsAtFront()
  arduino/smartcar/smartcar.ino
  arduino/smartcar/vehicle_config.json
Labels: sprint3

#76 Remove faulty code that led to joystick lag #75
  arduino/smartcar/smartcar.ino
Labels: bug, sprint3

#82 Change smartcar spawn location
  mod/mods/PocketParkingTerrain.tscn
  mod/mods/rroverr.gd
  mod/ppmod.pck
  mod/ppmod.zip
Labels: sprint3

#83 69 basic mapping and drive foward
  arduino/smartcar/smartcar.ino
Labels: sprint3

#87 Remove .import folder and .DS_Store files #79
  .gitignore
  arduino/.DS_Store
  arduino/smartcar/.DS_Store
  mod/.DS_Store
  mod/.import/.gdignore
  mod/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.md5
  mod/.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex
  mod/.import/wood.png-320746db63b5a5eb1bb7f02275994b36.etc2.stex
  mod/.import/wood.png-320746db63b5a5eb1bb7f02275994b36.md5
  mod/.import/wood.png-320746db63b5a5eb1bb7f02275994b36.s3tc.stex
  mod/.import/wood.png-320746db63b5a5eb1bb7f02275994b36.stex
Labels: sprint3

#85 84 terrain changes to accomendate mapping
  mod/icon.png
  mod/icon.png.import
  mod/mods/PocketParkingTerrain.tscn
  mod/mods/rroverr.gd
  mod/ppmod.pck
  mod/ppmod.zip
  mod/vehicle/PocketParkingVehicle.tscn
  mod/wood.png
  mod/wood.png.import
Labels: sprint3

#90 46 parking button
  SmartCarApplication/app/src/main/java/com/example/smartcarapplication/MainActivity.java
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: sprint3

#100 Fixed orientation of bent back IR sensor
  mod/mods/PocketParkingTerrain.tscn
  mod/ppmod.pck
  mod/vehicle/PocketParkingVehicle.tscn
Labels: bug, sprint4

#101 Update README.md
  README.md
Labels: documentation, sprint4

#102 Update README.md
  README.md
Labels: documentation, sprint4

#91 66 enable smartcar data visualization
  SmartCarApplication/app/build.gradle
  SmartCarApplication/app/src/main/AndroidManifest.xml
  SmartCarApplication/app/src/main/java/com/example/smartcarapplication/MainActivity.java
  SmartCarApplication/app/src/main/res/drawable/rounded_bg.xml
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
  SmartCarApplication/app/src/main/res/values/strings.xml
  SmartCarApplication/app/src/main/res/values/themes.xml
  SmartCarApplication/gradle/wrapper/gradle-wrapper.properties
  arduino/smartcar/smartcar.ino
  cmake-build-debug/CMakeFiles/clion-log.txt
Labels: sprint3, sprint4

#110 Update README.md
  README.md
Labels: documentation, sprint4

#107 98 button to retrieve car from parking
  SmartCarApplication/app/src/main/java/com/example/smartcarapplication/MainActivity.java
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
  arduino/smartcar/smartcar.ino
Labels: sprint4

#115 Update README.md
  README.md
Labels: documentation, sprint4

#117 Update README.md
  README.md
Labels: documentation, sprint4

#111 109 Increase distance when car stops
  arduino/smartcar/smartcar.ino
Labels: bug, sprint4

#114 Change color theme cruise control
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
Labels: enhancement, sprint4

#116 Readme status badges and further descriptions
  README.md
Labels: documentation

#120 Remove unnecessary variable declarations in Arduino sketch
  arduino/smartcar/smartcar.ino
Labels: enhancement, sprint4

#121 Update README.md to include setup instructions
  README.md
Labels: documentation, sprint4

#123 fix broken text, postion and colour of toggel button in the UI
  SmartCarApplication/app/src/main/res/drawable/rounded_bg_light.xml
  SmartCarApplication/app/src/main/res/layout/activity_main.xml
Labels: sprint4

#124 Update README.md Layout
  README.md
Labels: documentation, sprint4

#125 Polishing the README
  README.md
Labels: documentation, sprint4

#126 Change Fn + F3 to just F3
  README.md
Labels: documentation, sprint4

#128 remove checkObstacles() #127
  arduino/smartcar/smartcar.ino
Labels: bug, sprint4

#130 Add demo video image and text link #88
  README.md
Labels: documentation, sprint4

#131 Making demo vid fit to readme margins
  README.md
Labels: documentation, sprint4
